version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Expose Postgres port
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data
    networks:
      - my-network

  nodeapp:
    build: .
    ports:
      - "4000:4000"  # Expose the Node.js app port
    environment:
      DATABASE_HOST: postgres  # Connect to Postgres service
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root@root
      DATABASE_NAME: mydatabase
    depends_on:
      - postgres  # Ensure the database starts before the app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:  # Define volume to persist Postgres data
